config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :task

    get '/', to: "users#index", as: "sign_in"
    post '/sessions' => "sessions#create"
    get '/sign_up', to: 'users#new', as: 'new_users'
    post '/users' => "users#create"
    get '/dashboard' => "categories#index"

    get '/add_task/:category_id', to: 'task#new', as: 'add_task'
    post '/create_task/:category_id' => "task#create", as: 'create_task'
    get '/task/:id/edit', to: "task#edit", as: 'edit_category_task'

  get '/tasks/:category_id', to: 'task#index', as: 'category_tasks'
  get '/sign_out', to: 'sessions#destroy', as: :sign_out
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy
  validates :categories_name, presence: true
  validates :description, presence: true
end

app/models/session.rb
class Session < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  has_many :categories
  validates :email, uniqueness: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = current_user.categories
    @user = current_user
    @categories = @user.categories
  end

  def new
    @category = Category.new
  end

  def show
    @category = Category.find(params[:id])
  end
  def edit
    @category = Category.find(params[:id])
  end
  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to '/dashboard'
    else
      render :new
    end
  end
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to '/dashboard'
  end

  def create
    @category = current_user.categories.build(category_params)

    if @category.save
      redirect_to new_category_path, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  private


  def category_params
    params.require(:category).permit(:categories_name, :description)
  end

  def authenticate_user!
    redirect_to '/' unless current_user
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by(email:login_params[:email])
    if @user && @user.authenticate(login_params[:password])
      session[:user_id] = @user.id
      redirect_to '/dashboard'
    else
      flash[:error_login] = ['Invalid Username or Password']
      redirect_to '/'
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end

  private
  def login_params
    params.require(:login).permit(:email, :password)
  end
  
end

app/controllers/task_controller.rb
class TaskController < ApplicationController
  before_action :authenticate_user!
  def index
    @category = Category.find(params[:category_id])
    @tasks = @category.tasks.includes(:category)
  end
  def new
    @category = Category.find(params[:category_id])
    @task = @category.tasks.build
  end
  def show
    @task = Task.find(params[:id])
  end
  def edit
    @task = Task.find(params[:id])
  end
  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      flash[:success_updated] = ["Successfully Updated Task #{@task.task_name}"]
      redirect_to '/task/:id/edit'
    else
      flash[:error_update] = ["Failed to Updated Task #{@task.task_name}"]
    end
  end
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to "/tasks/:category_id"
  end

  def create
    @category = Category.find(params[:category_id])
    @task = @category.tasks.build(task_params)

    if @task.save
      redirect_to category_tasks_path(@category), notice: "Task Successfully Created"
    else
      flash[:error_creating] = [@task.errors.full_messages.join(' and ')]
      render :new
    end
  end

  private
  def authenticate_user!
    redirect_to '/' unless current_user
  end
  def task_params
    params.require(:task).permit(:task_name, :task_description, :task_date)
  end
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/sign_up'
      flash[:success_register] = ['Successfully Created Account']
    else
      flash[:error_register] = [@user.errors.full_messages.join(' and ')]
      redirect_to '/sign_up'
    end
  end
  def new
    @user = User.new
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_navbar.html.erb
<div class="nav-container flex bg-[#34495E] items-center p-4">
  <div class="flex-grow ml-4 flex">
    <ion-icon name="book-outline" class="mt-1 text-3xl text-yellow-500"></ion-icon>
    <h1 class="font-sans font-bold gradient-text ml-4 text-2xl bg-gradient-to-r from-cyan-400
     to-yellow-300">Journal App</h1>
  </div>

  <% if @user.username? %>
    <div class="flex items-center">
      <p class="text-yellow-100 mr-4">Welcome, @<%= @current_user.username %></p>
      <a href="<%= sign_out_path %>" data-method="delete" class="hidden text-white hover:text-gray-300 transition-opacity duration-500 ease-in-out">
        Sign Out
      </a>
    </div>
  <% else %>
    <%= link_to "Sign Up", new_users_path, class: "text-white hover:text-gray-300" %>
  <% end %>

  <ion-icon name="caret-down-circle-outline" id="user-icon" class="text-yellow-400 ml-4 cursor-pointer"></ion-icon>
</div>

<script>
document.addEventListener("DOMContentLoaded", function() {
  var userIcon = document.getElementById("user-icon");
  var signOutLink = document.querySelector(".nav-container a");

  userIcon.addEventListener("click", function() {
    // Toggle the display of the "Sign Out" link with animation
    const isHidden = signOutLink.classList.contains("hidden");
    signOutLink.style.display = isHidden ? "block" : "none";
    signOutLink.classList.toggle("hidden");
    userIcon.setAttribute("name", isHidden ? "caret-up-circle-outline" : "caret-down-circle-outline");
  });
});
</script>

app/views/categories/edit.html.erb
<div class="container bg-[#34495E] w-full mt-24 p-12 m-auto rounded-lg max-h-full shadow-lg shadow-gray-400">
  <h1 class="text-white text-2xl font-semibold mb-4">Edit Category Details</h1>

  <%= form_with model: @category do |form| %>
    <div class="mb-4">
      <label for="categories_name" class="text-white">Categories Name</label>
      <%= form.text_field :categories_name, class: "w-full p-2 rounded-md" %>
    </div>
    
    <div class="mb-4">
      <label for="description" class="text-white">Categories Description</label>
      <%= form.text_area :description, class: "w-full p-2 rounded-md" %>
    </div>
    
    <div class="mb-4">
      <%= form.submit 'Update Category', class: "bg-blue-500 text-white px-4 py-2 rounded-md" %>
    </div>
  <% end %>

  <div class="mt-4">
    <%= link_to 'Go to Dashboard', dashboard_path, class: "bg-green-500 text-white px-4 py-2 rounded-md" %>
  </div>
</div>

app/views/categories/index.html.erb
<%= render 'navbar' %>
<div class="container bg-[#34495E] w-4/6 mt-14 p-12 m-auto rounded-lg max-h-full shadow-lg shadow-gray-400">
   <div class="details text-white font-sans font-semibold flex">Entries <%= link_to new_category_path do %>
  <ion-icon name="add-circle-outline" class="mt-1"></ion-icon>
<% end %></div> 
<div class="scroll h-96 overflow-y-scroll">
   <div class="categories-container text-white font-sans font-semibold mt-4">

    <div class="all-categories flex flex-col">
      <% @categories.each do |category| %>
        <div class="category-item bg-gray-800 p-4 my-2 rounded-md">
      <span class="text-[#18FFFF]"><%= category.created_at.strftime('%B %d, %Y') %></span>
          <p><strong><%= category.categories_name %></strong></p>
          <p class="font-thin"><%= category.description %></p>

          <%= link_to 'Edit Category', edit_category_url(category.id), class: 'text-blue-500 mr-2' %>
          <%= link_to "Delete", category, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'text-red-500 mr-2' %>
          <%= link_to 'Add Tasks', add_task_path(category_id: category.id), class: 'text-green-500 mr-2' %>
          <%= link_to 'View Tasks', category_tasks_path(category_id: category.id), class: 'text-yellow-500' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

</div>

app/views/categories/new.html.erb
<div class="container bg-[#34495E] w-4/6 mt-24 p-12 m-auto rounded-lg max-h-full shadow-lg shadow-gray-400 grid grid-cols-1 md:grid-cols-2 gap-8">
  <div>
    <h1 class="text-white text-2xl font-semibold mb-4">New Category</h1>

    <%= form_with model: @category, url: categories_path do |form| %>
      <div class="mb-4">
        <%= form.label :categories_name, class: "text-white" %>
        <%= form.text_field :categories_name, class: "w-full p-2 rounded-md" %>
      </div>

      <div class="mb-4">
        <%= form.label :description, class: "text-white" %>
        <%= form.text_area :description, class: "w-full p-2 rounded-md" %>
      </div>

      <div class="btn flex">
     <div class="mb-4">
      <%= link_to 'Go to Dashboard', dashboard_path, class: "bg-green-500 text-white px-4 py-2 rounded-md" %>
       <%= form.submit 'Create Category', class: "bg-blue-500 text-white px-4 py-2 rounded-md" %>
    <% end %>
    <% if flash[:notice].present? %>
  <div class="display-notice text-green-500">
    <%= flash[:notice] %>
  </div>
<% end %>
    </div>
    
      </div>
  </div>

  <div>
    <% if @category.errors.any? %>
      <div id="error_explanation" class="text-white">
        <h2 class="text-xl font-semibold mb-4"><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

        <ul>
          <% @category.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JournalApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.tailwindcss.com"></script>
  <script>
    tailwind.config = {
      theme: {
        extend: {
          colors: {
            clifford: '#da373d',
          }
        }
      }
    }
  </script>
  <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
<style>
  .scroll {
    scrollbar-width: thin;
    scrollbar-color: #da373d #f1f1f1; /* Adjust the colors to your preference */
  }

  .scroll::-webkit-scrollbar {
    width: 12px;
  }

  .scroll::-webkit-scrollbar-thumb {
    background-color: #4DD0E1; /* Adjust the color to your preference */
    border-radius: 6px;
  }

  .scroll::-webkit-scrollbar-track {
    background-color: #f1f1f1; /* Adjust the color to your preference */
    border-radius: 6px;
  }
.gradient-text {
  background-clip: text;
  color: transparent;
}

</style>
  </head>

  <body class="bg-[#18FFFF]">
    <%= yield %>
  </body>
</html>

app/views/task/edit.html.erb
<div class="container bg-[#34495E] w-4/6 mt-24 p-12 m-auto rounded-lg shadow-lg shadow-gray-400">
  <h1 class="text-white text-2xl font-semibold mb-4">Edit Task</h1>

  <%= form_with(model: @task, url: task_path(@task), method: :patch) do |form| %>
    <div class="mb-4">
      <label for="task_name" class="text-white">Task Name</label>
      <%= form.text_field :task_name, class: "w-full p-2 rounded-md" %>
    </div>

    <div class="mb-4">
      <label for="task_description" class="text-white">Task Description</label>
      <%= form.text_area :task_description, class: "w-full p-2 rounded-md" %>
    </div>

    <div class="mb-4">
      <label for="task_date" class="text-white">Task Date</label>
      <%= form.date_field :task_date, class: "w-full p-2 rounded-md" %>
    </div>

    <div class="mb-4">
      <%= form.submit 'Update Task', class: "bg-blue-500 text-white px-4 py-2 rounded-md" %>
    </div>
  <% end %>

  <div class="errors text-green-500">
    <% if flash[:success_updated].present? %>
      <% flash[:success_updated].each do |message| %>
        <p><%= message %></p>
      <% end %>
    <% end %>

    <% if flash[:error_update].present? %>
      <% flash[:error_update].each do |error| %>
        <p><%= error %></p>
      <% end %>
    <% end %>
  </div>
</div>

app/views/task/index.html.erb
<div class="container bg-[#34495E] w-4/6 mt-10 p-12 m-auto rounded-lg max-h-[590px] shadow-lg shadow-gray-400 relative">
  <p class="text-lg font-semibold text-white mb-5">Category: <%= @category.categories_name %></p>
  <div class="scroll overflow-y-scroll max-h-[400px]">
    <% @tasks.each do |task| %>
      <div class="mb-6 border-b border-gray-300 pb-4">
        <p class="text-white"><strong>Task Name:</strong> <%= task.task_name %></p>
        <p class="text-white"><strong>Task Description:</strong> <%= task.task_description %></p>
        <p class="text-white"><strong>Task Date:</strong> <%= task.task_date %></p>
         <% if task.task_date.present? && task.task_date.future? %>
          <p class="text-white"><strong>Days Left:</strong> <%= (task.task_date.to_date - Date.today).to_i %> days</p>
        <% else %>
          <p class="text-green-500">Task has already Completed</p>
        <% end %>
        <div class="mt-2 flex">
          <%= link_to "Edit Task", edit_category_task_path(task.id), class: "text-blue-500 mr-4" %>
          <div class="text-green-500 mr-5">
            <a href="#" onclick="openTaskModal('<%= task.task_name %>', '<%= task.task_description %>', '<%= task.task_date %>')" class="text-green-500">View</a>
          </div>
          <%= link_to "Delete", task, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "text-red-500" %>
        </div>
      </div>
    <% end %>
  </div>

  <div id="taskModal" class="hidden fixed inset-0 bg-gray-800 bg-opacity-75 items-center justify-center">
    <div class="bg-white p-8 m-auto rounded-lg max-w-md">
      <h2 class="text-lg font-semibold mb-4">Task Details</h2>
      <p><strong>Task Name:</strong> <span id="modalTaskName"></span></p>
      <p><strong>Task Description:</strong> <span id="modalTaskDescription"></span></p>
      <p><strong>Task Date:</strong> <span id="modalTaskDate"></span></p>
      <p><strong>Days Left:</strong> <span id="modalDaysLeft"></span></p>
      <button onclick="closeTaskModal()" class="bg-blue-500 text-white px-4 py-2 rounded-md mt-4"> <%= link_to 'Close', category_tasks_path(category_id: @category.id), class: 'text-yellow-500' %></button>
    </div>
  </div>

  <div class="text-center grid">
    <%= link_to 'Create New Task', add_task_path(category_id: @category.id), class: "text-white bg-gradient-to-r from-cyan-500 to-blue-500 rounded-md p-2 text-white font-semibold mt-4 cursor-pointer" %>
     <%= link_to "Back", categories_path, class: "text-white mt-2" %>
  </div>

 <script>
  function openTaskModal(name, description, date) {
  document.getElementById('modalTaskName').innerText = name;
  document.getElementById('modalTaskDescription').innerText = description;
  document.getElementById('modalTaskDate').innerText = date;

  var taskDate = new Date(date);
  var currentDate = new Date();
  currentDate.setHours(0, 0, 0, 0); // Set hours, minutes, seconds, and milliseconds to 0 for consistent date comparison
  taskDate.setHours(0, 0, 0, 0);

  var daysLeft = Math.ceil((taskDate - currentDate) / (1000 * 60 * 60 * 24));

  if (daysLeft > 0) {
    document.getElementById('modalDaysLeft').innerText = daysLeft + ' days';
  } else if (daysLeft === 0) {
    document.getElementById('modalDaysLeft').innerText = 'Today';
  } else {
    document.getElementById('modalDaysLeft').innerText = 'Task has already Completed';
  }

  document.getElementById('taskModal').classList.remove('hidden');
}

function closeTaskModal() {
  document.getElementById('taskModal').classList.add('hidden');
}
</script>
</div>

app/views/task/new.html.erb
<div class="container bg-[#34495E] w-full mt-24 p-12 m-auto rounded-lg max-h-full shadow-lg shadow-gray-400">
  <h1 class="text-white text-2xl font-semibold mb-4">New Task for <%= @category.categories_name %></h1>

  <%= form_with(model: [@category, @task], url: create_task_path(@category), method: :post) do |form| %>
    <div class="mb-4">
      <%= form.label :task_name, class: "text-white" %>
      <%= form.text_field :task_name, class: "w-full p-2 rounded-md" %>
    </div>

    <div class="mb-4">
      <%= form.label :task_description, class: "text-white" %>
      <%= form.text_area :task_description, class: "w-full p-2 rounded-md" %>
    </div>

    <div class="mb-4">
      <%= form.label :task_date, class: "text-white" %>
      <%= form.date_field :task_date, class: "w-full p-2 rounded-md" %>
    </div>

    <div class="mb-4">
       <%= link_to 'Go Back', category_tasks_path, class: "bg-green-500 text-white px-4 py-2 rounded-md" %>
      <%= form.submit 'Create Task', class: "bg-blue-500 text-white px-4 py-2 rounded-md" %>
    </div>
  <% end %>
      <% if flash[:notice].present? %>
  <div class="display-notice text-green-500">
    <%= flash[:notice] %>
  </div>
<% end %>
  <div class="errors text-white">
    <% if flash[:error_creating].present? %>
      <% flash[:error_creating].each do |error| %>
        <p><%= error %></p>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container bg-[#34495E] w-max mt-36 p-12 m-auto rounded-lg shadow-lg shadow-gray-400 text-center">
    <h1 class="font-semibold font-sans text-2xl mb-3 text-white">LOGIN</h1>
<form action="/sessions" method="POST" class="grid">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
        
       <div class="relative mb-4">
   <input  class="bg-transparent  border-b-2 border-white text-white hover:bg-[#546E7A] pl-10 pr-4 py-2" 
    type="email" name="login[email]"  placeholder="Email">
      <ion-icon name="mail-outline" class="absolute left-3 top-1/2 transform -translate-y-1/2 text-white text-lg"></ion-icon>
       </div> 

  <div class="relative mb-4">
         <input class="bg-transparent border-b-2 border-white p-2 text-white hover:bg-[#546E7A] pl-10 pr-4 py-2" type="password" name="login[password]" placeholder="Password">
      <ion-icon name="lock-closed-outline" class="absolute left-3 top-1/2 transform -translate-y-1/2 text-white text-lg"></ion-icon>
       </div> 
    <input class="bg-gradient-to-r from-cyan-500 to-blue-500 ... rounded-md p-2 text-white font-semibold mt-4 cursor-pointer" type="submit" name="submit" value="Login">
</form>
<div class="errors mt-5 text-[#EF5350]">
    <% if flash[:error_login]%>
    <% flash[:error_login].each do |error|%>
    <p><%= error%></p>
    <%end%>
    <%end%>
</div>
<div class="sign-up mt-10 flex justify-center">
    <p class="text-sm text-white">Don't Have an Account?</p> 
      <p class="text-sm ml-2 text-[#18FFFF] cursor-pointer"><%= link_to "Sign Up", new_users_path %></p>
</div>
</div>

app/views/users/new.html.erb
<div class="container bg-[#34495E] w-max mt-24 p-12 m-auto rounded-lg shadow-lg shadow-gray-400 text-center">
  <h1 class="text-white">REGISTER</h1>
<form action="/users" method="POST" class="grid">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">

         <div class="relative mb-4">
      <input type="username" name="user[username]" placeholder="Username"  class="bg-transparent  border-b-2 border-white text-white hover:bg-[#546E7A] pl-10 pr-4 py-2" >
      <ion-icon name="people-outline" class="absolute left-3 top-1/2 transform -translate-y-1/2 text-white text-lg"></ion-icon>
       </div> 

         <div class="relative mb-4">
        <input type="email" name="user[email]" placeholder="Email"  class="bg-transparent  border-b-2 border-white text-white hover:bg-[#546E7A] pl-10 pr-4 py-2" >
      <ion-icon name="mail-outline" class="absolute left-3 top-1/2 transform -translate-y-1/2 text-white text-lg"></ion-icon>
       </div> 

     <div class="relative mb-4">
    <input type="password" name="user[password]" placeholder="Password"  class="bg-transparent  border-b-2 border-white text-white hover:bg-[#546E7A] pl-10 pr-4 py-2" >
      <ion-icon name="lock-closed-outline" class="absolute left-3 top-1/2 transform -translate-y-1/2 text-white text-lg"></ion-icon>
       </div> 

       <div class="relative mb-4">
     <input type="password" name="user[password_confirmation]" placeholder="Confirm Password"  class="bg-transparent  border-b-2 border-white text-white hover:bg-[#546E7A] pl-10 pr-4 py-2" >
      <ion-icon name="lock-closed-outline" class="absolute left-3 top-1/2 transform -translate-y-1/2 text-white text-lg"></ion-icon>
       </div> 

    <input class="bg-gradient-to-r from-cyan-500 to-blue-500 ... rounded-md p-2 text-white font-semibold mt-4 cursor-pointer" type="submit" name="submit" value="Register">
</form>
<div class="sign-up mt-10 flex justify-center">
    <p class="text-sm text-white">Already Have an Account?</p> 
        <p class="text-sm ml-2 text-[#18FFFF]"><%= link_to "Sign In", sign_in_path%></p>
</div>

<div class="errors text-[#EF5350]">
  <% if flash[:error_register].present? %>
    <% flash[:error_register].each do |error| %>
      <p><%= error %></p>
    <% end %>
  <% end %>
</div>
<div class="success text-[#18FFFF]">
  <% if flash[:success_register].present? %>
    <% flash[:success_register].each do |success| %>
      <p><%= success %></p>
    <% end %>
  <% end %>
</div>
</div>